# Gridding

This chapter contains different options available under Gridding menubar in CDT. We can create gridded data from CDT stations data format using spatially inerpolation. Under this menubar, we can merge rainfall data with station data and create merged dataset. We can also merge temperature data with reanalysis data. We also have the option of scaling merged data and doing cross-validation of rainfall and temperature data.

Topics included in this chapter are:

* Spatial interpolation
* Merging rainfall data
* Merging temperature data
* Scale merged data
* Merging - Cross-validation

## Spatial interpolation
We can conduct spatial interpolation of CDT station data format with different time frequency to create gridded data. Using 7 different interpolation techniques we can do the interpolation. Either we can define a grid by ourselves  or mention a netCDF file which will be used to specify the grid for the interpolated data. After we are done with interpolating, we can also plot this newly created dataset.


## Merging rainfall data
There are 3 steps that need to be executed for merging rainfall data with station data.

1. Compute bias coefficients
2. Apply bias correction
3. Merging data

### Compute bias coefficients

### Apply bias correction

### Merging data

## Merging tremperature data
There sare 5 steps in merging observational temperature data with reanalysis data. These 5 steps are:

1. Compute downscaling coefficients
2. Reanalysis downscaling
3. Compute bias coefficients
4. Apply bias correction
5. Merging data

### Compute downscaling coefficients

### Reanalysis downscaling

### Compute bias coefficients

### Apply bias correction

### Merging data

## Scale merged data

## Merging cross-validation.
We can cross-validate both the p0recipitation and temperature data.

### Precipitation data

### Temperature data

## Exercise